### ISSUE TITLE
Explicit resource binding for UAVs

### ISSUE THREAD

**Issue by hekota** [llvm/wg-hlsl#34]
Explicit resource binding support for [[milestone] Compile a runnable shader from clang](llvm/wg-hlsl#7):
- [x] Parse explicit resource binding (llvm/llvm-project@e3fd0b20)
- [x] Write resource binding to metadata - UAVs only (llvm/llvm-project@618e5006)
- [x] llvm/llvm-project#57886

**Comment by bogner** [comment]
This should all be in place as of llvm/llvm-project#104447
