### ISSUE TITLE
Explicit resource binding for SRV, CBV and samplers

### ISSUE THREAD

**Issue by hekota** [llvm/wg-hlsl#36]
Explicit resource binding support for [[milestone] Compile particle_life.hlsl](llvm/wg-hlsl#20):
- [x] Parse explicit resource binding (llvm/llvm-project@e3fd0b20)
- [x] llvm/llvm-project#57886
- [ ] Write resource binding to metadata - SRVs, constant buffer and samplers (sample are not used in `particle_life.hlsl`, but we might as well add them here) - llvm/llvm-project#104447

Resource binsing for UAVs is included here: llvm/wg-hlsl#34

**Comment by damyanp** [comment]
This is all done, or work to complete it is being tracked elsewhere.
