### ISSUE TITLE
[HLSL] Define attributes for texture type and dimension

### ISSUE THREAD

**Issue by bogner** [llvm/wg-hlsl#39]
In order to retain sufficient information to build dxil handles at code gen, resources need attributes that specify the texture type and texture dimension. This is especially important because we plan to remove the resource attribute, which contain the resource kind. Without the resource kind, these two new attributes are needed to build the dxil handle.

When texture resources are declared, the proper texture type and texture dimension attributes should be applied.

AC
- A proposal is created in `wg-hlsl`

**Comment by damyanp** [comment]
This is covered by other work now.
