### ISSUE TITLE
[Sema] Update resource class attribute tests

### ISSUE THREAD

**Issue by bob80905** [llvm/wg-hlsl#43]
Currently, the hlsl::resource_class attribute is applied onto field decls in tests created in https://github.com/llvm/llvm-project/pull/97103. This will soon be an incorrect representation of how the attribute will be applied to resource types, because @hekota will be changing these attributes to apply to the field type instead.
So, the hlsl_resource_class* tests need to be retroactively updated to account for this change, and any necessary expected check lines need to be adjusted.

**Comment by hekota** [comment]
This has been fixed by #107160
