### ISSUE TITLE
Type trait rules for buffer types

### ISSUE THREAD

**Issue by damyanp** [llvm/wg-hlsl#64]
The one compiler implemented trait we need is to determine if a type `T` is scalarized layout compatible with a 1-4 element vector for some element type (i.e. is it 1-4 elements of the same data type).

We could technically implement that in a header, but it would be gross and potentially buggy because we would need to enumerate each of the builtin types that are allowed in vectors.

**Comment by llvm-beanz** [comment]
I think the only trait we really need is a shortcut for a struct that is scalarized layout compatible with a 1-4 element vector. The other traits that I think we would use can be implemented in Clang in a header:

Some template goop that could be put in a trait header:
```c++
template<typename T>
struct IsVectorType {
  constexpr static bool Value = false;
};

template <typename T, uint N>
struct IsVectorType<T __attribute__((ext_vector_type(N)))> {
  constexpr static bool Value = true;
};

template <typename T>
struct VectorTypeInfo;

template <typename T, uint N>
struct VectorTypeInfo<T __attribute__((ext_vector_type(N)))> {
  using Type = T;
  constexpr static uint Size = N;
};

export uint Test() {
  if (IsVectorType<VectorTypeInfo<float2>::Type>::Value) 
    return VectorTypeInfo<uint3>::Size;
  if (IsVectorType<float4>::Value) 
    return VectorTypeInfo<uint2>::Size;
};
```
[Compiler Explorer](https://godbolt.org/z/fT6exoM9o)

**Comment by bob80905** [comment]
Assuming these will be used for resource element type validation, I think I would prefer a single type trait that checks both that the vector is 1-4 elements, and that each element is at most 32 bits.

**Comment by bob80905** [comment]
Correct, my comment was based on a previous misunderstanding.

**Comment by llvm-beanz** [comment]
I think we've settled on a design for the current buffers where we don't need traits outside the vector element types and sizes. So I'm going to close this.
